### ISSUE TITLE
Request: Add examples of weird postmodifiers "ago", "else"

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#11]
* He_A arrived_P [[five_Q minutes_C]_C ago_R]_T (I consider "ago" a postposition)

   Cf. p. 12: "He_A is_F [nine_Q years_C]_T old_S" (age construction—another weird postmodifier)

* Does_F [everyone_C else_E]_A want_P pizza_A?

**Comment by nschneid** [comment]
@dotdv do these analyses look OK?

**Comment by dotdv** [comment]
Yes, makes sense to me.

**Comment by dotdv** [comment]
Added in "interesting examples"

**Comment by nschneid** [comment]
> He_A arrived_P [[five_Q minutes_C]_C ago_R]_T (I consider "ago" a postposition)

In retrospect, should it be [five_Q minutes_C ago_R]_T, without a C-within-C?

**Comment by dotdv** [comment]
right, I corrected it
