### ISSUE TITLE
Classifiers

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#13]
How are classifiers like "a **piece/sheet** of paper" handled? These are light/transparent nouns, so one option might be "a_E piece_C of_R paper_C". Or Q seems reasonable: "a_E piece_Q of_R paper_C"? "[a_E piece_C]_Q of_R paper_C"?

**Comment by omriabnd** [comment]
I think the Q analysis is the most straightforward option.
