### ISSUE TITLE
Free relative clauses

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#15]
pp. 27–28:

> Tell_P me_A [what_A happened_P]_A
> I_A wonder_P [where_A he is going]_A

This structure seems off because it doesn't distinguish the focused argument of the embedded clause. To give another example: "I know what you gave to John" focuses the thing given as the object of "know", whereas "I know who you gave it to" focuses the recipient and "I know you gave it to John" does not focus on either argument. What about

Tell_P me_A [what_C [(what)_A happened_P]_E]_A

I wonder [where_C [he_A is going_P (where)_A]_E]_A

I know [what_C [you gave_P (what)_A [to_R John_C]_A]_E]_A

**Comment by omriabnd** [comment]
I like this.
Dotan?

**Comment by dotdv** [comment]
OK, I'll make the change.

**Comment by nschneid** [comment]
I just heard a presentation where somebody used a free relative clause inside a free relative clause: She said she'd talk about "how what we've been building is of use for the field".

how_C [[what_C [we_A 've_F been_F building_P (what)_A]_E]_A is_F [of use]_S [for_R the_E field_C]_A (how)_D]_E

I think it works. :)

**Comment by omriabnd** [comment]
Added to interessting cases. Dotan, did you already make the fix in the "Fused E Scenes" section?

**Comment by nschneid** [comment]
I just added the simple free relative clause examples under "Question words".

The fused E scenes section still needs to be updated—perhaps that depends on #32.
