### ISSUE TITLE
Cross-sentence annotation?

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#16]
> A UCCA annotation task consists of the annotation of multiple sentences, usually a paragraph or several paragraphs long. When you receive a task, take a few minutes to read the entire text, in order to understand the context.

Does a unit in the foundational layer ever include material from multiple sentences?

**Comment by nschneid** [comment]
It appears that yes, there are some examples under Interjections (p. 26). I think it's worth discussing under what circumstances a unit may cross sentences.

**Comment by nschneid** [comment]
(Maybe another example: speech verb + quotation that spans multiple sentences)

**Comment by omriabnd** [comment]
Right. In addition, remote units can be taken from any sentence in the passage.

**Comment by nschneid** [comment]
Could there be a section in the guidelines that gives some examples of cross-sentence remotes?

**Comment by nschneid** [comment]
> E.g. if there is an imperative and then "you" appears much later in the passage, should that be treated as a remote participant, or should it be implicit?

Omri says yes, by the current guidelines, remotely linking to any overt occurrence of "you" is better than an implicit unit.

**Comment by dotdv** [comment]
> Could there be a section in the guidelines that gives some examples of cross-sentence remotes?

Yes I also had in mind that we should. For example, annotators tend to ask what to do in cases where two or more references are optional? should we ask for the closest possible? if so what should we do if both references seem equally close?

**Comment by omriabnd** [comment]
Dotan, could you add a section with examples of cross-sentence annotation, notably: speech verb + quotation that spans multiple sentences and cross-sentence remotes.

**Comment by dotdv** [comment]
Yes, added "cross-sentence annotation". Regarding cross-sentence Remotes, do you agree with this example?: 
[Jake asked Mary [if she heard the evening news]_A]_H. [Mary said she didn't (heard)_P (news)_A]_H but_L [(she)_A will [make sure]_D to_F (heard)_P (news)_A]_H when_L [she arrives home]_H

**Comment by nschneid** [comment]
The tenses are weird; simpler to use the present tense (as if describing the plot of a story):

Jane asks Mary if she has heard the evening news. Mary says she hasn't but will make sure to when she arrives home.

I agree with the UCCA analysis.

**Comment by nschneid** [comment]
I've added an imperative example where a "you" in another sentence can be added as remote.

**Comment by dotdv** [comment]
> Jane asks Mary if she has heard the evening news. Mary says she hasn't but will make sure to when she arrives home.

Corrected, thanks!

**Comment by omriabnd** [comment]
I think the guidelines should be: use remotes over implicits wherever
possible, but if there is no explicit mention of the entity in question, or
the text doesn't specify which entity that is, use implicits.

**Comment by dotdv** [comment]
> I think the guidelines should be: use remotes over implicits wherever possible, but if there is no explicit mention of the entity in question, or the text doesn't specify which entity that is, use implicits.
>

First sorry, I accidentally mentioned "thank you" as an example of an imperative. What I actually meant to do was raise two issues: 
the imperatives section: will probably need to be updated (since we ask there to add an Implicit A),
but also the  "thanks/thank you" section: since also there we ask to add Implicits (two IMP to "thanks" and one to "thank you"). So Omri, I understand from your answer that both passages will need to be revised.

**Comment by omriabnd** [comment]
we could just say in a note that they should be remotes if the person
thanking or is being thanked appear in the passage.
