### ISSUE TITLE
Number part of measurement

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#17]
On p. 8, the number part of a measure phrase is usually E: e.g. [three_E kilos_C]_Q of_R apples_C.  However, footnote 2 explains that distance measures are different, e.g.

He ran [100_Q meters_C]_A

which a student flagged as confusing. Is this because the measure phrase is serving directly as a participant, and it is desirable to mark it somehow as a quantity? Why not [100_E meters_C]_A+Q? That way "100 meters of rope" can be [100_E meters_C]_Q of_R rope_C.

**Comment by omriabnd** [comment]
I'm not sure if this is not just leftovers from the previous version.
Dotan?

**Comment by dotdv** [comment]
Makes sense to me.

**Comment by omriabnd** [comment]
I suggest the following solution that will allow us to keep a quantity within a non-scene unit invariably a Q, and not a Q or an E depending on the context (this is less confusing). I suggest:
"[100_Q meters_C]_Q [of_R rope_C]_C"
"[100_Q nautical_E miles_C]_Q [of_R rope_C]_C"
"[exactly_E 100_Q meters_C]_Q [of_R rope_C]_C" 

In the case of Scenes, I suggest avoiding the use of Q entirely, to avoid confusion. That is, even the case (#28) where there is a number/quantity of times the scene has happened. As in:

"I watched the movie twice_D"
"John_A did_F plenty_D of_R work_P"
"I watched the movie [for two hours]_T" (duration!)

We analyze them as D.

**Comment by nschneid** [comment]
Sounds good to me.
