### ISSUE TITLE
"in which", "to whom"

### ISSUE THREAD

**Issue by omriabnd** [UniversalConceptualCognitiveAnnotation/docs#20]
From Nathan:

I'm not sure it makes sense to treat "in which" as a multiword item—the preposition is really acting compositionally and orthogonally to the relativizer. It could be "the earth out of which the plants sprang", for example. You even get this with verb- and adjective-selected prepositions, e.g. "everyone to whom John is close" = "everyone whom John is close to" = "everyone John is close to". Why not:

the city_C [ [in_R (city)_C]_A which_R John_A lives_S ]_E
I'm not sure how this works in Hebrew: I would guess "העיר שבה גר ג'ון"? Can you say "העיר שג'ון גר בה"??? Either way, I assume it involves a normal pronominally-inflected preposition and relativizer ש-.

everyone_C [ [to_R (everyone)_C]_A whom_R John_A is_F close_S ]_E
Is this "כל מי שלו קרוב ג'ון"?

**Comment by dotdv** [comment]
Yes, I understand. Omri, I can go over the guidelines and correct where this appears, maybe also add a small section. What do you think?
Re  p.7 I agree. Omri, I think 'whom' should be R, no?

**Comment by omriabnd** [comment]
Yes. Please fix the guidelines to reflect this.
Thanks
