### ISSUE TITLE
Noun scenes with scene modifiers

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#22]
p. 18 addresses noun scenes. One of them has an adjective ("accurate") tagged as D. What about an adjectival modifier that is more scene-like, e.g. "a cringe - inducing presentation by the mayor"? Would this be

[a_E [cringe_A inducing_P (presentation)_A]_E presentation_C]_P [by_R the_E mayor_C]_A

with a remote to indicate that the head of the adjectival modifier is essentially an argument of it?

Another possibility that avoids using E for a scene modifier:

[a_E presentation_C]_P [cringe_A inducing_P (presentation)_A]_D  [by_R the_E mayor_C]_A

**Comment by nschneid** [comment]
Actually, I guess cringing is an act which requires a cringer, and inducing is causation, so something like

[a_E [(IMP)_A cringe_P inducing_D (presentation)_A]_E presentation_C]_P [by_R the_E mayor_C]_A

or 

[a_E presentation_C]_P [(IMP)_A cringe_P inducing_D (presentation)_A]_D [by_R the_E mayor_C]_A

?

**Comment by nschneid** [comment]
Considered and rejected: [a_E [cringe_P inducing_D]_E presentation_C]_P

The solution, though somewhat unintuitive: [a_E]_H- [cringe_P inducing_D]_H [presentation_C]_-H
This avoids a tricky issue of defining which modifier scenes are D and which are H.

TBD: the argument structure of "cringe-inducing".

**Comment by nschneid** [comment]
Should we include implicit/remote participants of nominalized events/states like "__cringe__-inducing" or "express __discontent__"?

**Comment by omriabnd** [comment]
We need to ask the FrameNet people about the typology of DNIs vs. CNIs, and can we define a well-defined sub-class of implicits to annotate, deferring the annotation of others.

**Comment by omriabnd** [comment]
I talked with Miriam. It seems DNIs are just as tricky to get as INIs. We'll have to do strictly with CNIs for now.
