### ISSUE TITLE
Request: more examples of secondary verbs

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#23]
try to?, refuse to?, decide to?, etc.

**Comment by nschneid** [comment]
Dixon (SAEG p. 98): classes of secondary verbs which do not introduce additional roles:

> - MODALS, e.g. will, can, should, might, ought to, must 
> - SEMI-MODALS, e.g. be going to, be able to, have got to 
> - BEGINNING, e.g. begin, start, finish, complete, continue (with) 
> - TRYING, e.g. try, attempt, succeed, fail, practise
> - HURRYING, e.g. hurry (over/with), hasten (over/with), dawdle (over) 
> - DARING—dare, venture

pp. 100-101: classes of secondary verbs which may introduce an additional role

> - WANTING (with a number of subdivisions; see §6.2.1), e.g. want, wish (for); hope (for); need, require; expect; intend; pretend
> - POSTPONING, e.g. postpone, delay, defer, avoid
> - MAKING, e.g. make, force, cause, tempt; let, permit, allow, prevent, spare, ensure 
> - HELPING, e.g. help, aid, assist
> - SEEM, e.g. seem, appear, happen, look 
> - MATTER—matter, count

pp. 97-98 list the primary verb classes. These include *attention, thinking, deciding, speaking, and happening*. Thus, some subclasses of cognitive/mental verbs are considered primary, while others are secondary. If Dixon's distinction is intended for UCCA, I think the division needs to be clarified in the guidelines.

**Comment by omriabnd** [comment]
We should more examples of the sub-classes. We could go by Dixon's English sub-classes of PRIMARY-B and SECONDARY.
