### ISSUE TITLE
Sorkin example

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#24]
We went through one of the Sorkin passages in class. [Here is our best attempt.](https://github.com/UniversalConceptualCognitiveAnnotation/docs/files/2380671/asr_example_passage_nathan.pdf)
 It raised a few questions:

1. Is "Syracuse University" unanalyzable? p. 14 says names in general are not, but "University of Texas" is. (Also: What about "Texas A&M University"?)

2. "his freshman year": unclear how to treat the possessive (#3)

3. "It was a devastating setback": It_A was_S [[a_E setback_C]_P devastating_D]_A ? Because "devastating" is deverbal should it also be scene-evoking?

4. "He wanted to be an actor": [an [actor]_P+A]_S ? Cf. #25 and the "taxi driver" guidelines example, where the noun names a profession is considered to evoke the scene of performing that profession. (But would "professor" also be considered scene-evoking given that the activity is not "professing"?)

5. "...did not allow students to take the stage until they completed all the core freshman classes": The negation seems to scope over "until", but "allow" is arguably a secondary verb. Does the negation belong only to the "take the stage" scene and not to the completion-of-classes scene? (#29)

6. Should "classes" be considered scene-evoking? Should "completed" be its secondary verb? Does "freshman" merely modify or is it a participant of classes?

**Comment by nschneid** [comment]
> Is "Syracuse University" unanalyzable? p. 14 says names in general are not, but "University of Texas" is. (Also: What about "Texas A&M University"?)

It is analyzable (#30).

> Should "classes" be considered scene-evoking?

Omri said yes.

**Comment by nschneid** [comment]
> "It was a devastating setback": It_A was_S [[a_E setback_C]_P devastating_D]_A ? Because "devastating" is deverbal should it also be scene-evoking?

Related to #22. "Devastating" cannot be both a process and a D. Probably leave as above.

**Comment by omriabnd** [comment]
> "It was a devastating setback": It_A was_S [[a_E setback_C]_P devastating_D]_A ? Because "devastating" is deverbal should it also be scene-evoking?
Yes but not because it's deverbal, but because there's a state involved (someone is devastated)

> "...did not allow students to take the stage until they completed all the core freshman classes": The negation seems to scope over "until", but "allow" is arguably a secondary verb. Does the negation belong only to the "take the stage" scene and not to the completion-of-classes scene? (#29)
We do not resolve such fine scope distinctions, so we always put the negation in the Scene level.

> "...did not allow students to take the stage until they completed all the core freshman classes": The negation seems to scope over "until", but "allow" is arguably a secondary verb. Does the negation belong only to the "take the stage" scene and not to the completion-of-classes scene? (#29)
Good question. My tendency would be to say that "class" is scene-evoking and that "completed" is a secondary verb.
