### ISSUE TITLE
Partitives/subsets

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#26]
Perhaps I missed it, but I don't think the guidelines address examples like:

* some of the books are missing
   - Note that this presumes a relevant set of books. It entails, but is not equivalent to, "some books are missing".
  - "All of the books are missing" does not necessarily entail "all books are missing".
* half/a third/20% of the books are missing
* 4 of the 5 books are missing
* the rest of the books are missing

Cf. SNACS analysis under [Quantity](http://flat.nert.georgetown.edu/Quantity/#018) and [Whole](http://flat.nert.georgetown.edu/Whole/#027).

**Comment by nschneid** [comment]
Suggestion based on today's discussion in class:

When referring to a subset of items, if two quantities or sets are given and only one of them has a descriptor with it, use a remote to associate it with the other:

- [[most_Q (books)_C]_C of_R [the_E books_C]_E]_A are missing
   * Contrast: [most_Q books_C]_A are missing
- [[4_Q (books)_C]_C of_R [the_E 5_Q books_C]]_A are missing
   * Note that there may be a singular/plural mismatch between the primary and remote descriptor:
      [[1_Q (books)_C]_C of_R [the_E 5_Q books_C]]_A is missing
- TODO: set proportions (half/a third/20%/the rest)—can't say "a third books of the books", so a remote feels weird
- TODO: rates: "4 in/out_of 5 books are worthless", "I read a book a day", "I read 2 books per day"
- TODO: non-set wholes: "most of the foliage is green", "most of the land is unplotted"
- TODO: collective/framal wholes: "most of the group/company"
- TODO: composite measures: "a third of a meter long"

**Comment by nschneid** [comment]
Most of the examples are plain quantities rather than subquantities of a definite NP superset. "Portions" had the_F rest_Q [of_R the_F cake_C]_C. I added some_Q [of_R the_F cats_C]_C and 80%_Q [of_R women_C]_C. Also, elsewhere, the example "one of Selznick’s productions" appears. This solution collapses the two kinds of quantities, which is probably a good idea (though SNACS distinguishes them).

There may be unresolved TODOs above, but I'm not going to worry about them now (they may be rare anyway).

**Comment by omriabnd** [comment]
OK. We should add rare examples to the interesting examples appendix to
prevent the guidelines from over-inflating.
