### ISSUE TITLE
Part-whole

### ISSUE THREAD

**Issue by dotdv** [UniversalConceptualCognitiveAnnotation/docs#27]
_Nathan's comment from the guidelines: \nss{Then how to distinguish `I bought bicycle spokes' from `I bought a bicycle with spokes'? These are quite different meanings. I'm not sure a uniform treatment of part-whole relations across paraphrases is possible in the foundational layer without sacrificing other things.}_

I agree. Omri correct me if I'm wrong but I think the intention of this guideline wasn't to refer to cases where it's very clear what the center should be (e.g I bought [a [bike]_C [with spokes]_E] and actually also 'I bought [bicycle_E spokes_C]_A') but rather to deal with cases like: I ate [a piece of cake] where one could argue that  both 'cake' and 'piece' can answer "what did John eat" and therefore can both be Cs. So first I think that this section requires that we give whole scenes as examples and also that we clarify what are the types of cases we are referring to

Personally in 'piece of cake' my intuitive response would have been to mark the part rather than the whole as the C (e.g 'piece' as the C in the example above ). 
And also in other examples:
As ship was found [at_R the_E bottom_C of_R [the sea]_E]_A
 [two_Q puzzle_E pieces_C]_A are missing

**Comment by nschneid** [comment]
So, "I ate 3 kinds of cookies" implies "I ate cookies", not (without strong context) "I ate 3 kinds". But "How many kinds of cookies did you eat?" focuses on "kinds", and cannot be shortened as "How many cookies did you eat?".

**Comment by omriabnd** [comment]
Make sure the guidelines has examples of all these:

Qs:
-- Aggregates (bunch, group, collection)
-- Quantities (flood, number, scores)
-- Portions (half, rest)
-- Unitizers (glass, bottle, box)

Two Cs:
-- Relational Parts, defined only with respect to the other C (top, bottom, tip, front, side), **but not "car window"**

Es:
-- Types (breed, class, ilk, kind), similar to "The person John"
-- Evaluations (gem, idiot)
