### ISSUE TITLE
Degree/intensifier adverbs

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#28]
Should adverbs that modify adjectives or adverbs ("very", "quite", "really", "slightly", etc.) be D or E? If D I would guess:

"a very hot plate": a_E [very_D hot_C]_E plate_C

"a very beautiful wedding": [a_E wedding_C]_P [very_D beautiful_C]_D

"You won quite handily": You_A won_P [quite_D handily_C]_D

**Comment by dotdv** [comment]
In principle, a D can only modify a P or S so we don't add it to non-Scene units (there is one section that breaks this rule: "D in coordination" p.20). 
So If the adverb modifies a P/S then indeed it can be marked D: 
"a_E [very_D hot_S (plate)_A]_E plate_C
But if it modifies a C then I think our solution would be to mark it E: 
 [a_E]_{P-} [very_E beautiful_C]_D [wedding]_{-P}
Omri, do you agree?



**

**Comment by omriabnd** [comment]
Yes

בתאריך יום א׳, 16 בספט׳ 2018, 07:15 AM, מאת dotdv ‏<notifications@github.com

**Comment by nschneid** [comment]
You_A won_P [quite_E handily_C]_D
?

**Comment by dotdv** [comment]
Yes

**Comment by nschneid** [comment]
Sounds good. Could you add these examples to the guidelines?

**Comment by dotdv** [comment]
Yes, how about I add this section below and disable the "quantity adverbs" section for now?:
 
_Intensifiers and degree adverbs
If the intensifier/degree adverb modifies a P/S then it should be marked D:
"a_E [very_D hot_S (plate)_A] E plate_C

But if it modifies a C then it should be marked E:
[a_E]{P-} [very_E beautiful_C]D [wedding]{-P} 
You_A won_P [quite_E  handily_C]_D_ 

Maybe later as a second step we can add a section that will determine the difference  between Quantifiers and Degree and also how to deal with these when they help form a time unit. 

John was able to save a little bit of money
John is a little bit nervous
Time: I can stay [for a little bit], but then will have to go
John did plenty of work today
There are plenty of apples 
John hasn't seen Mary much this year
There is much to do
How many times did you visit her this week?
There were many people at the party

**Comment by nschneid** [comment]
Yes, the relationship to quantity is an interesting issue. Particularly "John did plenty of work", where an activity is conceptualized as a thing which can be quantified (via a light verb construction).

Roughly speaking I think we could say that a modifier that answers "how much/many?" is Q provided that it modifies a C. I could see either

John_A did_F [plenty_Q of_R work_C]_P
or
John_A did_F plenty_D of_R work_P
(paraphrase: "John worked plenty.")

**Comment by omriabnd** [comment]
Resolution:
treat this as event quantification, i.e., Q, and note contrast with durations (T)

John_A did_F plenty_Q of_R work_P

**Comment by nschneid** [comment]
On p. 22 I drafted an explanation of the degree modifiers. Haven't written anything about quantities.
