### ISSUE TITLE
Request: Example of modal that scopes over multiple parallel scenes

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#29]
Similar to how it works with elaborators of multiple units joined by a connector, I assume modals that apply to both parallel scenes should go outside:

"You shouldn't drink and drive": [should_D n't_D [You_A drink_P]_H and_L [(You)_A drive_P]_H]_H

"You cannot have dessert until you've eaten your vegetables" [can_D not_D [You have dessert]_H until_L [you 've eaten your vegetables]_H]_H

**Comment by nschneid** [comment]
Or, in the case of syntactic coordination of two scene-phrases, perhaps shared arguments should be pulled out to the containing scene, instead of using a remote?:

[You_A should_D n't_D [drink_P]_H and_L [drive_P]_H]_H

**Comment by omriabnd** [comment]
``[The$_E$ [decline$_C$ and$_N$ death$_C$]$_C$ ]$_P$ [of$_R$ a$_E$ monarch$_C$]$_A$'' (1 Scene)

**Comment by omriabnd** [comment]
Dotan, do you remember why we commented them out?

**Comment by nschneid** [comment]
A possibility (that was apparently considered in draft guidelines; see the above LaTeX) is a compound scene where multiple processes are coordinated:

You_A should_D n't_D [drink_C and_N drive_C]_P

**Comment by omriabnd** [comment]
Resolution: leave the guidelines as is.
