### ISSUE TITLE
Unanalyzability

### ISSUE THREAD

**Issue by omriabnd** [UniversalConceptualCognitiveAnnotation/docs#30]
Unify chapter 9 and 6, consider "the real deal" as unanalyzable.

**Comment by nschneid** [comment]
An initial attempt to clarify the criteria for unanalyzability—thoughts?:

If somebody who hadn't heard the expression or name before would be able to figure out what/who it is based on the meanings of the individual words/parts, it is probably analyzable. 
Unanalyzable expressions include:

- personal names like "John Q. Smith" (excluding titles like "Dr.", "St.", "President", "Queen", which are E)
- titles of works of art/literature/law: *A Tale of Two Cities* (book), *Marbury v. Madison* (court case)
- idiomatic multiword expressions with unpredictable (opaque or not-fully-transparent) meaning: "hot dog" (food), "give up" ('quit'), "the real deal", "kick the bucket" ('die'). This includes phrases from another language: "crème de la crème" (in English).

Proper names of places, organizations, and events are often analyzable, as are many specialized/technical terms: 
- Silicon_E Valley_C
- Microsoft_C Corporation_E
- University_C of_R California_E
- UC_C Berkeley_C
- Society_C of_R [Linguistics_E Undergraduate_E Students_C]_E
- World_E War_C II_Q
- [natural_E language_C]_A processing_P (?)
- time_E signature_C (music)

However, a name embedded within another name generally is not:

- [St. Lawrence UNA]_E River_C

**Comment by nschneid** [comment]
Another unanalyzable MWE: "English horn" (a kind of musical instrument not necessarily made in England)

**Comment by omriabnd** [comment]
The criterion is: are you able to recognize the semantic input of the part in the whole. Names are an exception. 
By that token, "French horn" is analyzable. 

Add a criterion: if something is named after something else, that something else is not analyzed internally:
[St._E Lawrence_C]_A was a kind man

But:
I live [by_R the_E [St. Lawrence]_E River_C]_A
I live [in_R [St. Paul]_C]_A

So no inner analysis of St. Paul / St. Lawrence.

Dotan?

**Comment by nschneid** [comment]
Instead of "named after something else", "named after a completely different kind of thing (e.g. city named after person)".

**Comment by dotdv** [comment]
I live [by_R the_E [St. Lawrence]_E River_C]_A
I live [in_R [St. Paul]_C]_A
So no inner analysis of St. Paul / St. Lawrence.
Dotan?

Yes, that's what I tell annotators if they ask. Sure we can add something about it.
