### ISSUE TITLE
Multiple parallel scenes in relative clause

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#34]
A student asks about the example: "people who are stuck on themselves, rude, or downright arrogant".

Presumably "stuck", "rude", and "arrogant" evoke parallel scenes. I'm not sure whether the relator "who" and copula "are" should be included in the scene with "stuck" only, shared as a remote to the second and third, or if there should be another layer of nesting: 

a. people_C [[who_R are_F (people)_A stuck_S...]_H [(people)_A rude_S]_H or_L [(people)_A ...arrogant_S]_H]_E
b. people_C [[who_R are_F (people)_A stuck_S...]_H [(who)_R (are)_F (people)_A rude_S]_H or_L [(who)_R (are)_F (people)_A ...arrogant_S]_H]_E
c. people_C [who_R are_F [[(people)_A stuck_S...]_H [(people)_A rude_S]_H or_L [(people)_A ...arrogant]_H]_H]_E

@dotdv what do you think?

**Comment by nschneid** [comment]
I remembered #31 

> * A parallel scene (H) cannot have smaller parallel scenes immediately under it.

which I guess rules out (c). But (a) and (b) are pretty awkward, so I wonder if the rule should be relaxed. Or should the function words be inside the unit with the parallel scenes and linker?

d. people_C [who_R are_F [(people)_A stuck_S...]_H [(people)_A rude_S]_H or_L [(people)_A ...arrogant_S]_H]_E

?

**Comment by dotdv** [comment]
Y

> I remembered #31
> 
> > * A parallel scene (H) cannot have smaller parallel scenes immediately under it.
> 
> which I guess rules out (c). But (a) and (b) are pretty awkward, so I wonder if the rule should be relaxed. Or should the function words be inside the unit with the parallel scenes and linker?
> 
> d. people_C [who_R are_F [(people)_A stuck_S...]_H [(people)_A rude_S]_H or_L [(people)_A ...arrogant_S]_H]_E

Yes, I think option **d** here above is how I'd mark it. My only question is whether the F should be outside the first scene like you marked in d or rather in it . Personally I think I like it out like in d, but since I don't think we had a chance so far to discuss this specific case (where the F can be outside the H scenes) maybe we should make sure we agree on one option. @omriabnd  do you agree  with version d and more specifically do you agree with the "are" being on the same level with the 3 H scenes (instead of being included in the first scene?)

**Comment by omriabnd** [comment]
> And BTW @nschneid from what I know we don't add Fs as Remotes (but do add As Ds and Ts), so 
even if the Function word "are" were included only in the first scene, I don't think you'd need to add it to the rest.
I agree.

Dotan, could you add this to the interesting examples?

**Comment by omriabnd** [comment]
I agree that (d) is the right analysis and we shouldn't duplicate R/F.

**Comment by dotdv** [comment]
But then what do we do in cases such as: "John asked Mary if she heard about the concert. Mary answered that she did" 
It seems problematic to annotate it without the R:
"...Mary answered that she did (heard)_P (concert)_A"

**Comment by nschneid** [comment]
Indeed, that seems problematic. I think relators should be included in participant remotes, at least.

I don't have a strong opinion on relativizers (people who_R are rude...).

**Comment by nschneid** [comment]
Semantic roles don't always capture the preposition's full lexical semantics, though: 

"I found the cat under the couch. The dog too." — this implies that the dog is also UNDER the couch, not simply located with respect to the couch.

**Comment by omriabnd** [comment]
I see what you mean, but I think taking larger remotes, and asking the
annotator to decide when to take the R and when not complicates things. We
could always write a script that gets us the Rs of the original unit if we
wanted them. More fine-grained distinctions than that belong to a finer
layer.

**Comment by nschneid** [comment]
Good point. Though remotes display as copies, of course underlyingly they're edges, so associated modifiers can be accessed.
