### ISSUE TITLE
Does "use"/"using" always evoke a scene?

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#36]
Consider:

1. He broke the window **with** a hammer. – seems like "with a hammer" is a clear participant
2. He broke the window **using** a hammer.
3. He broke the window **by using** a hammer. – "by" presents the use of the hammer as a means
4. He **used** a hammer to break the window.
   [He_A used_P [a hammer]_A [(He)_A to break_P [the window]_A]_A – this analysis seems reasonable, but I could also see an argument that "used" is a secondary verb.

**Comment by omriabnd** [comment]
I would say the first 3 don't evoke a scene (instruments), while the last
one has two Scenes with a purposive Linker. I agree "used' could be
analyzed as a secondary verb, but my feeling is that this option will be
less immediate for annotators.

**Comment by nschneid** [comment]
Would you make "using" a relator in (2)? What about (3)?

**Comment by omriabnd** [comment]
Yes. Relator. I agree #3 is borderline between a Scene and not a Scene.

**Comment by nschneid** [comment]
So with the non-scene interpretation of (3), both "by" and "using" would be relators?

**Comment by omriabnd** [comment]
yes

**Comment by omriabnd** [comment]
Dotan, could you add these as examples to the guidelines?

**Comment by dotdv** [comment]
Added these examples under "instruments" (do you agree with this title or have a better idea?) in "interesting examples". 
Regarding example 3: I marked 'by' and 'using' separately as Rs. "he broke the window [by_R using_R a hammer]_A
