### ISSUE TITLE
Multisentence passage example

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#39]
Since all the guidelines examples are single phrases or sentences, my students weren't sure whether a sentence with multiple parallel scenes/linkers should be wrapped in its own parallel scene, or whether sentence-internal linkers should remain at the top level. This could be addressed with a ~3-sentence example at the end of the guidelines.

(This could help illustrate #16 too.)

**Comment by dotdv** [comment]
So far we've been asking annotators to keep multiple parallel scenes and linkers on the top level without adding a parent parallel unit. Yes, I also agree this should be clarified in the guidelines.

**Comment by nschneid** [comment]
It says "Sequences of Multiple Parallel Scenes", which I think is fine (I prefer "sequences" to "strings").

**Comment by omriabnd** [comment]
Changed to "Sequences of Multiple Parallel Scenes"
