### ISSUE TITLE
Scene-evoking participant nominals

### ISSUE THREAD

**Issue by dotdv** [UniversalConceptualCognitiveAnnotation/docs#42]
-Then could the principle be: nouns which denote a participant by virtue of being currently, previously, or habitually involved in a certain kind of **activity/profession** ("teacher", "professor", "author", "therapist", "candidate", "servant", "retiree", "plaintiff", "recipient", "beneficiary", "rabbi", "pedestrian") evoke a P scene of performing that activity/profession
   * only human/animate?
   * [A_E [priest_P+A]_C]_A walked_P [into_R a_E bar_C]_A
   * a lung specialist: a_E lung_E [specialist_P+A (lung)_A]_C ?
- nouns denoting an individual (human/animate?) participant of a **kinship relation** or **static social or organizational relationship** ("father", "friend", "boss", "employee", "chairman") should evoke an S scene of the relationship
   * If used in a possessive construction, the possessive marker is R
      - John_A 's_R father_S+A
      - my_A+R father_S+A
      - John_A has_R no_D father_S+A
- unless the noun is used as a title, like Chairman Mao, Prof. Smith, or Father Smith (priest)

_Originally posted by @nschneid in https://github.com/UniversalConceptualCognitiveAnnotation/docs/issues/4#issuecomment-421592136_

**Comment by dotdv** [comment]
I created a new issue for this to make sure we don't get confused and address it properly

**Comment by dotdv** [comment]
And I think this part of the dicussion you had in issue 25 "the judge: scene evoking?" is also relevant:
![untitled1](https://user-images.githubusercontent.com/43039183/47267086-92609e80-d547-11e8-933c-502daee69009.png)

**Comment by omriabnd** [comment]
Updated the guidelines.
