### ISSUE TITLE
When should Relators be included in the associated unit?

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#43]
This has arisen in #35 and similar.

Suggestion: Instead of a distinction between Scene units, where they do mark participants etc., and non-Scene units, make the distinction about Center vs. non-Center.

thinking_P [about_R the problem_C]_A
a cup_C of_R water_C
Queen_C [of_R England_C]_E
the_E house_C [on_R Main Street]_E [between_R [the_E school_C]_C and_N [the_E church_C]_C]_E

There may need to be a special treatment of the Cs in coordination (e.g. coordinated PPs).

**Comment by nschneid** [comment]
I am thinking_P [about_R French_C]_A
I am thinking_P [about_R [(I)_A learning_P French_A]_C]_A
—this is nicely parallel with
a story_C [about_R French_C]_E
a story_C [about_R [(IMP)_A learning_P French_A]_C]_E


For coordination I think we could do:

It happens [[after_R noon_C]_C and_N [before_R midnight_C]_C]_T (PP coordination)

It happens [[before_R (midnight)_C]_C and_N [after_R midnight_C]_C]_T (P coordination)

**Comment by omriabnd** [comment]
Agreed.

**Comment by dotdv** [comment]
So this means that when a Relator relates to a P/S it should be included as well, right?: 
series [of lectures]_P?
And in this example from the guidelines (p.18): ``The_E outbreak_C]_D [of_R the_E War_C ]_P''

**Comment by omriabnd** [comment]
Yes

**Comment by nschneid** [comment]
> So this means that when a Relator relates to a P/S it should be included as well, right?

I could go either way here.

With articles changing to F, I suppose it could be:

The_F outbreak_D of_R the_F War_P

or

The_F outbreak_D [of_R the_F War_C]_P

**Comment by omriabnd** [comment]
if we're going for simplicity of the guidelines, how about we just write:
always put Rs with their objects. So:

The_F outbreak_D [of_R the_F War_C]_P
Cup_C [of_R water_C]_C

Dozens_Q [of_R people_C]_C

The two latter cases will then be normalized to Cup_C of_R water_C by the
normalization script, but annotators shouldn't worry about that.

**Comment by omriabnd** [comment]
Resolution: they should always go with their prepositional object.
Dotan, could you change the guidelines to reflect this?

**Comment by dotdv** [comment]
> I am thinking_P [about_R [(I)_A learning_P French_A]_C]_A

I think the convention we've been following so far is to annotate it without a unifying C: I am thinking_P [about_R (I)_A learning_P French_A]_A
The only place where we ask to add a unifying C is when the R relates to mutiple units that carry an identicle role  (section Elaboration of/by a Coordination.):  "John met [with_R [Jane_C and_N Mary_C]_C]_A"

**Comment by dotdv** [comment]
Do you agree with this annotation? 
	``[a group]$_Q$ [of$_R$ journalists$_C$]$_{P+A}$``

**Comment by nschneid** [comment]
Why not

[a group]_Q [of_R [journalists_P+A]_C]_C

which would get simplified to

[a group]_Q of_R [journalists_P+A]_C

?

**Comment by omriabnd** [comment]
> So I think we just need to decide if we want to change this convention or not.

We do not want to change it.
