### ISSUE TITLE
VP Ellipsis

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#49]
"[You're only saying this] because [John told you to]"

Omri's solution is to have the entire first scene unit as a remote in the second.

If we want to use remotes of minimal size, I would think it should be:

[You're only saying this]_H because_L [John_A told_P you_A [(you)_A to_F (only)_D (saying)_P (this)_A]_A]_H

@omriabnd, what's the Hebrew example that would be problematic?

**Comment by omriabnd** [comment]
The Hebrew is
אתה עושה את זה כי יוסי אמר לך

That is, there is no 'to'. So you can't add sub-units to it.

In general, your solution is dependent on putting the 'to' in the A, and we
usually say where you place the F is inconsequential.

**Comment by nschneid** [comment]
Ah, I see: the point is that every non-leaf unit must have at least one non-remote subunit, which is only the case in English because of "to".

Should we formalize the rule as, for a unit to have children, at least one of them must be non-remote AND must have a category other than F?

**Comment by omriabnd** [comment]
yes. i'll do that.

please also close any issues you see were resolved.
thanks

**Comment by omriabnd** [comment]
We'll enforce this in the app. Added to the asana.
