### ISSUE TITLE
Purpose clauses

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#5]
Guidelines request: An example of a purpose clause adjunct where the matrix clause has an overt subject. I *think* it should be a remote `A` of the purpose scene, but am not 100% sure. Here is our best attempt from class:

![image](https://user-images.githubusercontent.com/985263/45194822-b596ef00-b222-11e8-8488-db04333da40e.png)

**Comment by omriabnd** [comment]
Right.

**Comment by omriabnd** [comment]
Added
