### ISSUE TITLE
Multiple Elaborators and nesting

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#6]
We're confused about whether multiple layers of nested non-scene units are permissible with elaborators like possessives. With certain compound nominals it feels tempting to have a unit with one or more elaborators that is further elaborated in a parent unit, but perhaps this is a bad idea.

![image](https://user-images.githubusercontent.com/985263/45195109-24287c80-b224-11e8-920e-1e3e41fefe86.png)

Should chains of multiple `C` edges always be forbidden? I guess alternatives to the above are:

[my_S+A (engine)_A]_E [broken_S (engine)_A]_E car_E engine (all `E` relations are sisters)

[my_S+A (cone)_A]_E [ice cream]_E cone_C

**Comment by omriabnd** [comment]
We would annotate it the "alternatives" you mentioned.
I should say that chains of Cs are not always forbidden but only if a
Center has exactly one Center child. (i.e., it can have more children, but
none of the others should be C).

**Comment by nschneid** [comment]
OK, so would "the open restaurant bathroom window" (assuming the window is open) be

the_E [open_S (window)_A]_E [restaurant_E bathroom_C]_E window_C

?

**Comment by omriabnd** [comment]
Exactly

בתאריך שבת, 8 בספט׳ 2018, 09:02 PM, מאת Nathan Schneider ‏<
notifications@github.com>:
