### ISSUE TITLE
Directions and multiword prepositions

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#9]
On p. 23:

> Sometimes a directional word is followed by a preposition, both pertaining to the same Participant. In such cases we mark them both as a multiword unanalyzable R:
> 
>   - "Mary went [[up to UNA]_R John's room]_A"
>
> it is important in such cases to distinguish between the case of a multi-worded preposition and the case of an adverbial followed by a single-word preposition:
> 
>   - "John_A went_P away_D [to_R college]_A" ("away" and "to" should not be considered as one relation, but rather away (from some unspecified place) and to college)

By what criterion is this distinction made? I don't think of "up to" in the above example as a multiword preposition. Note that either part is optional: "Mary went up" (implicit destination) or "Mary went to John's room" (no directional particle).

A clear directional multiword preposition is "out of": Mary went out of the room / *Mary went of the room. "Away from" is borderline, but I consider it a multiword when it means the opposite of "toward".

**Comment by nschneid** [comment]
I also don't understand why "later in" is treated as a complex preposition on p. 28:

[[later in]_R 1998_C]_T, John bought a car

"Earlier" and "later" are adverbs and can be used with other temporal prepositions: e.g. "later on Friday". One could argue that the adverb modifies the PP; compare "**right** before/after the party", "the nail went **right** through the wood". (See also "just_D around_S [the corner]_A", p. 20.) So something like

[later_D in_R 1998_C]_T, John bought a car

would be preferable.

(This is not to be confused with colloquial "later on", where the "on" is not followed by an object but provides some sort of aspectual emphasis: "Let's get drinks later on." It would be reasonable to call this a multiword T.)

**Comment by omriabnd** [comment]
Yes. I think that's right.
Thanks

**Comment by dotdv** [comment]
I rephrased the two relevant paragraphs in the directional words section (the rephrased parts are in bold). tell me what you think: 

**In cases where a directional word participates in a multi-worded preposition, we will mark the whole phrase as an unanalyzable  R:

``Mary walked [[out of UNA]_R John's  room]_A``
``John lives [[across from UNA]_R Mary_C]_A``
``John looked at the picture [[in front of UNA]_R him_C]_A``**

It is important in such cases to distinguish between the case of a multi-worded preposition and the case of an adverbial followed by a single-word preposition:

``John_A went_P away_D [to_R college]_A`` **(see that each part in this example still makes sense when standing alone: you can say "John went away" and "John went to college". But in the case of a multi-worded preposition it won't work: "John walked out of the room"  cannot be reduced to "John walked of the room")**

**Comment by dotdv** [comment]
I rephrased the two relevant paragraphs in the directional words section. tell me what you think: 

In cases where a directional word participates in a multi-worded preposition, we will mark the whole phrase as an unanalyzable  R:

``Mary walked [[out of UNA]_R John's  room]_A``
``John lives [[across from UNA]_R Mary_C]_A``
``John looked at the picture [[in front of UNA]_R him_C]_A``

It is important in such cases to distinguish between the case of a multi-worded preposition and the case of an adverbial followed by a single-word preposition:
``John_A went_P away_D [to_R college]_A`` ( see that each part in this example still makes sense when standing alone: you can say "John went away" and "John went to college". But in the case of a multi-worded preposition it won't work: "John walked out of the room"  cannot be reduced to "John walked of the room")

**Comment by dotdv** [comment]
I edited one of the examples I gave above
